### ISSUE TITLE
.Gitignore

### ISSUE THREAD

**Issue by ludoviclaffineur** [IRISIB/JukeBox#1]
Je viens de cloner le projet. Je pense que le .gitignore n'est pas correct...

![capture d ecran 2015-02-14 a 11 44 13](https://cloud.githubusercontent.com/assets/1901914/6199354/dcea4164-b43e-11e4-900d-8c9b8346fee2.png)

http://stackoverflow.com/questions/3719243/recommended-gitignore-file-for-python-projects

Faut faire cela très vite, sinon vous allez avoir des merging très douloureux.

**Comment by Makcime** [comment]
Done ;)

2015-02-14 11:48 GMT+01:00 Ludovic Laffineur notifications@github.com:
